### PR TITLE
Closes #552 Java 17 migration

### LINKED ISSUE #552: Java 17 Migration
As a developer I want to keep up with "new" Java LTS Releases.

Please compile everything with Java 17

### PR DESCRIPTION
**Pull request by arolfes**
https://sonarcloud.io/summary/new_code?id=arolfes_TaskanaAdapter&branch=java_17

---
 
### For the submitter:
- [ ] I updated the [documentation](https://taskana.atlassian.net/wiki/spaces/TAS/overview) and will supply links to the specific files
- [x] I did not update the [documentation](https://taskana.atlassian.net/wiki/spaces/TAS/overview)
- [x] I included a link to the [SonarCloud branch analysis](https://taskana.atlassian.net/wiki/spaces/TAS/pages/1019969636/SonarCloud+Integration)
- [ ] I added a description of changes on the [current release notes](https://taskana.atlassian.net/wiki/spaces/TAS/pages/1281392672/Current+Release+Notes+Taskana)
- [ ] I did not update the [current release notes](https://taskana.atlassian.net/wiki/spaces/TAS/pages/1281392672/Current+Release+Notes+Taskana)
- [ ] I put the ticket in review

### Verified by the reviewer:
- [ ] Commit message format → ADPT-XXX: Your commit message.
- [ ] Submitter's update to [documentation](https://taskana.atlassian.net/wiki/spaces/TAS/overview) is sufficient
- [ ] SonarCloud analysis meets our standards
- [ ] Update of the [current release notes](https://taskana.atlassian.net/wiki/spaces/TAS/pages/1281392672/Current+Release+Notes+Taskana) reflects changes
- [ ] PR fulfills the ticket
- [ ] Edge cases and unwanted side effects are tested
- [ ] Readability

### CODE REVIEW

**Comment by ryzheboka** [comment]
Thanks for the changes :) Could you please rebase this PR? We would integrate it in the next release

**Comment by arolfes** [comment]
> Thanks for the changes :) Could you please rebase this PR? We would integrate it in the next release

Hy @ryzheboka , I do it in the afternoon :)

**Comment by arolfes** [comment]
Hello @ryzheboka 

when running the tests in my repo, some weird exceptions are thrown around
See: https://github.com/arolfes/TaskanaAdapter/actions/runs/6423423737/job/17441897279
Example `Caused by: pro.taskana.workbasket.api.exceptions.WorkbasketNotFoundException: Workbasket with key 'invalidWorkbasketKey' and domain 'null' was not found.`

What I also don't understand is why the Github action doesn't get executed.

**Comment by gitgoodjhe** [comment]
> Hello @ryzheboka
> 
> when running the tests in my repo, some weird exceptions are thrown around See: https://github.com/arolfes/TaskanaAdapter/actions/runs/6423423737/job/17441897279 Example `Caused by: pro.taskana.workbasket.api.exceptions.WorkbasketNotFoundException: Workbasket with key 'invalidWorkbasketKey' and domain 'null' was not found.` I need some time to investigate this.
> 
> What I also don't understand is why the Github action doesn't get executed.

Hi @arolfes 

Is this really an "error" error? Because there is a test "should_LogError_When_TaskCreationFailedInTaskana()" which tests the logging of this exact exception (The error message gets set in the CamundaTaskEvents, so if someone looks into the database they can see why the processing of the event failed):
   assertThat(failedEvents)
        .extracting(CamundaTaskEvent::getError)
        .allMatch(
            error ->
                error.contains(
                    "{\"name\":"
                        + "\"pro.taskana.workbasket.api.exceptions.WorkbasketNotFoundException\","
                        + "\"message\":"
                        + "\"Workbasket with key 'invalidWorkbasketKey' "
                        + "and domain 'null' was not found.\"}"));

**Comment by arolfes** [comment]
Hello @gitgoodjhe,
ah this would explain why the build is still successfull :)

**Comment by ryzheboka** [comment]
Hi @arolfes , could you merge this PR if everything is ok for you?

**Pull request merged**
